version: '3.1'

services:
  clinic_api:
    image: clinic-api:latest
    ports:
      - 7000:${API_PORT}
    env_file: .docker.env
    networks:
      - postgres_db_net
      - mongo_db_net
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:14
    hostname: CLINIC_DB_POSTGRES
    restart: always
    env_file: .docker.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - postgres_db_net

  mongo:
    image: mongo:5.0
    hostname: CLINIC_DB_MONGO
    restart: always
    env_file: .docker.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - mongo_db_net

networks:
  mongo_db_net:
    name: 'mongo_db_network'
    driver: 'bridge'

  postgres_db_net:
    name: 'postgres_db_network'
    driver: 'bridge'